server:
  shutdown: graceful
  port: 8080

spring:
  profiles:
    active: 'local'
    group:
      local: common,local
      dev: common,dev
      prod: common,prod

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: info, caches, configrop, mappings, env, refresh, health, prometheus, busrefresh
